### ISSUE TITLE
Unable to choose a single number.

### ISSUE THREAD

**Issue by Arqib** [gabfl/roulette#4]
It throws the following error:
Traceback (most recent call last):
  File "/usr/local/bin/roulette", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/roulette/play.py", line 425, in main
    firstPlay(bank=args.bank,
  File "/usr/local/lib/python3.9/dist-packages/roulette/play.py", line 407, in firstPlay
    play(type_=type_,
  File "/usr/local/lib/python3.9/dist-packages/roulette/play.py", line 351, in play
    valid = isSpecificChoiceValid(specificChoice)
TypeError: isSpecificChoiceValid() missing 1 required positional argument: 'type_'

**Comment by gabfl** [comment]
@Arqib thank you for the report, the issue has been patched and a new version 1.5 has been pushed.

Feel free to re-open the ticket if needed

**Comment by Arqib** [comment]
Thanks for the quick response and fix.

**Comment by Arqib** [comment]
And please add a Street bet option or alternatively a multiple straight bet
option.

**Comment by gabfl** [comment]
HI, feel free to file a pull request if you would like but unfortunately I am not able to add any new feature at this time

**Comment by Arqib** [comment]
Ok, thanks for the reply.
